fx_version 'cerulean'
game 'gta5'

author 'Vcore'
description 'FxManifest Generated by VCore, All Files Sorted and Ready for Exicution <Replace with Your Resource Description>'
version '1.0.0'

client_scripts {
    'client/client.lua',
    'client/effects.lua'
}

server_scripts {
    'server/server.lua'
}

shared_scripts {
    'shared/config.lua'
}

ui_page     'html/index.html'

files {
    'html/images/*.png',
    'html/index.html',
    'html/script.js',
    'html/style.css'
}
